[package]
name = "mjml_nif"
version = "1.0.0"
authors = ["Pavel Makarenko"]
edition = "2018"

[lib]
name = "mjml_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
mrml = { version = "1.2.2", features = ["parse", "render"], default-features = false }
